const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=process.argv[2]; if(!root)throw Error('Project path required');
const base='Assets/_Project/Map01',scene='Assets/_Project/Scenes/Maps/Map01_ForestFootprints.unity';
const guid=p=>crypto.createHash('md5').update('ShadowVale.Map01:'+p).digest('hex');
function meta(p,folder=false){let f=path.join(root,p+'.meta');if(!fs.existsSync(f)){fs.mkdirSync(path.dirname(f),{recursive:true});let importer=p.endsWith('.cs')?'MonoImporter:\n  externalObjects: {}\n  serializedVersion: 2\n  defaultReferences: []\n  executionOrder: 0\n  icon: {instanceID: 0}\n':p.endsWith('.mat')?'NativeFormatImporter:\n  externalObjects: {}\n  mainObjectFileID: 2100000\n':p.endsWith('.asmdef')?'AssemblyDefinitionImporter:\n  externalObjects: {}\n':'DefaultImporter:\n  externalObjects: {}\n';fs.writeFileSync(f,'fileFormatVersion: 2\nguid: '+guid(p)+'\n'+(folder?'folderAsset: yes\n':'')+importer+'  userData: \n  assetBundleName: \n  assetBundleVariant: \n');}return /guid: ([a-f0-9]+)/.exec(fs.readFileSync(f,'utf8'))[1];}
function write(p,s){fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),s);meta(p);}
function sweep(p){meta(p,true);for(const entry of fs.readdirSync(path.join(root,p),{withFileTypes:true})){if(entry.name.endsWith('.meta'))continue;const n=p+'/'+entry.name;if(entry.isDirectory())sweep(n);else meta(n);}}
// Keep the scene reference tied to a real imported TextAsset, never a hard-coded GUID.
const contentPath=base+'/Generated/Map01Content.json';
fs.mkdirSync(path.dirname(path.join(root,contentPath)),{recursive:true});
fs.copyFileSync(path.join(root,'Assets/StreamingAssets/Content/fallback_bundle.json'),path.join(root,contentPath));
if(!fs.existsSync(path.join(root,contentPath+'.meta'))) fs.writeFileSync(path.join(root,contentPath+'.meta'),'fileFormatVersion: 2\nguid: '+guid(contentPath)+'\nTextScriptImporter:\n  externalObjects: {}\n  userData: \n  assetBundleName: \n  assetBundleVariant: \n');
const contentGuid=meta(contentPath);
const mats={earth:[.24,.29,.17],path:[.49,.39,.24],grass:[.25,.4,.22],bark:[.25,.2,.12],leaf:[.15,.31,.23],stone:[.35,.4,.33],wood:[.38,.29,.18],canvas:[.46,.49,.3],water:[.12,.39,.4],metal:[.25,.31,.29],paper:[.82,.77,.56],gold:[1,.69,.2],nam:[.15,.48,.48],hung:[.68,.57,.25],enemy:[.57,.29,.23]};
const matGuids={};for(const [name,c]of Object.entries(mats)){let p=base+'/Generated/Materials/Source_'+name+'.mat';write(p,'%YAML 1.1\n%TAG !u! tag:unity3d.com,2011:\n--- !u!21 &2100000\nMaterial:\n  serializedVersion: 8\n  m_ObjectHideFlags: 0\n  m_CorrespondingSourceObject: {fileID: 0}\n  m_PrefabInstance: {fileID: 0}\n  m_PrefabAsset: {fileID: 0}\n  m_Name: '+name+'\n  m_Shader: {fileID: 4800000, guid: '+(name==='gold'?'650dd9526735d5b46b79224bc6e94025':'933532a4fcc9baf4fa0491de14d08ed7')+', type: 3}\n  m_ValidKeywords: []\n  m_InvalidKeywords: []\n  m_LightmapFlags: 4\n  m_EnableInstancingVariants: 1\n  m_DoubleSidedGI: 0\n  m_CustomRenderQueue: -1\n  stringTagMap: {}\n  disabledShaderPasses: []\n  m_SavedProperties:\n    serializedVersion: 3\n    m_TexEnvs: []\n    m_Ints: []\n    m_Floats:\n    - _Smoothness: 0.08\n    - _Surface: 0\n    - _ZWrite: 1\n    - _Cull: 2\n    m_Colors:\n    - _BaseColor: {r: '+c[0]+', g: '+c[1]+', b: '+c[2]+', a: 1}\n    - _Color: {r: '+c[0]+', g: '+c[1]+', b: '+c[2]+', a: 1}\n');matGuids[name]=meta(p);}
let id=5000000;const objects=[],parts=[],roots=[],shapes=[],points=[],guards=[];
const v=(a)=>'{x: '+a[0]+', y: '+a[1]+', z: '+a[2]+'}';
const q=a=>{let x=a[0]*Math.PI/360,y=a[1]*Math.PI/360,z=a[2]*Math.PI/360;return '{x: '+(Math.sin(x)*Math.cos(y)*Math.cos(z)+Math.cos(x)*Math.sin(y)*Math.sin(z))+', y: '+(Math.cos(x)*Math.sin(y)*Math.cos(z)-Math.sin(x)*Math.cos(y)*Math.sin(z))+', z: '+(Math.cos(x)*Math.cos(y)*Math.sin(z)-Math.sin(x)*Math.sin(y)*Math.cos(z))+', w: '+(Math.cos(x)*Math.cos(y)*Math.cos(z)+Math.sin(x)*Math.sin(y)*Math.sin(z))+'}';};
function obj(name,p=[0,0,0],scale=[1,1,1],parent=null,layer=0){const o={go:id++,tr:id++,name,p,scale,parent,layer,children:[],components:[],rot:[0,0,0]};o.components.push(o.tr);if(parent)parent.children.push(o.tr);else roots.push(o.tr);objects.push(o);return o;}
function comp(o,type,label,fields){const cid=id++;o.components.push(cid);parts.push('--- !u!'+type+' &'+cid+'\n'+label+':\n  m_ObjectHideFlags: 0\n  m_CorrespondingSourceObject: {fileID: 0}\n  m_PrefabInstance: {fileID: 0}\n  m_PrefabAsset: {fileID: 0}\n  m_GameObject: {fileID: '+o.go+'}\n'+fields);return cid;}
function script(o,name,fields){return comp(o,114,'MonoBehaviour','  m_Enabled: 1\n  m_EditorHideFlags: 0\n  m_Script: {fileID: 11500000, guid: '+meta(base+'/Runtime/'+name+'.cs')+', type: 3}\n  m_Name: \n  m_EditorClassIdentifier: \n'+fields);}
const env=obj('01 • Terrain & collision'),detail=obj('02 • Foliage & set dressing');
script(env,'ForestNavigation','');
function shape(name,p,s,mat,type='cube',solid=true,parent=null){const o=obj(name,p,s,parent||(solid?env:detail),solid?9:0);let mesh={cube:10202,sphere:10207,cylinder:10206,capsule:10208}[type];comp(o,33,'MeshFilter','  m_Mesh: {fileID: '+mesh+', guid: 0000000000000000e000000000000000, type: 0}\n');comp(o,23,'MeshRenderer','  m_Enabled: 1\n  m_CastShadows: 1\n  m_ReceiveShadows: 1\n  m_DynamicOccludee: 1\n  m_StaticShadowCaster: 0\n  m_MotionVectors: 1\n  m_LightProbeUsage: 1\n  m_ReflectionProbeUsage: 1\n  m_RayTracingMode: 2\n  m_RayTraceProcedural: 0\n  m_RenderingLayerMask: 1\n  m_RendererPriority: 0\n  m_Materials:\n  - {fileID: 2100000, guid: '+matGuids[mat]+', type: 2}\n  m_StaticBatchInfo:\n    firstSubMesh: 0\n    subMeshCount: 0\n  m_StaticBatchRoot: {fileID: 0}\n  m_ProbeAnchor: {fileID: 0}\n  m_LightProbeVolumeOverride: {fileID: 0}\n  m_ScaleInLightmap: 1\n  m_ReceiveGI: 1\n  m_PreserveUVs: 0\n  m_IgnoreNormalsForChartDetection: 0\n  m_ImportantGI: 0\n  m_StitchLightmapSeams: 1\n  m_SelectedEditorRenderState: 3\n  m_MinimumChartSize: 4\n  m_AutoUVMaxDistance: 0.5\n  m_AutoUVMaxAngle: 89\n  m_LightmapParameters: {fileID: 0}\n  m_SortingLayerID: 0\n  m_SortingLayer: 0\n  m_SortingOrder: 0\n  m_AdditionalVertexStreams: {fileID: 0}\n');if(solid)comp(o,65,'BoxCollider','  m_Material: {fileID: 0}\n  m_IncludeLayers:\n    serializedVersion: 2\n    m_Bits: 0\n  m_ExcludeLayers:\n    serializedVersion: 2\n    m_Bits: 0\n  m_LayerOverridePriority: 0\n  m_IsTrigger: 0\n  m_ProvidesContacts: 0\n  m_Enabled: 1\n  serializedVersion: 3\n  m_Size: {x: 1, y: 1, z: 1}\n  m_Center: {x: 0, y: 0, z: 0}\n');shapes.push({name,p,s,mat,type,solid});return o;}
function point(key,label,kind,p,items=[],radius=3){let o=obj(key+' • '+label,p,[1,1,1],detail);script(o,'ForestPoint','  id: '+key+'\n  label: '+JSON.stringify(label)+'\n  kind: '+kind+'\n  radius: '+radius+'\n  used: 0\n  items:'+(items.length?'\n'+items.map(([item,count])=>'  - item_id: '+item+'\n    count: '+count+'\n').join(''):' []\n'));points.push({key,label,kind,p});return o;}
function crate(key,label,kind,x,z,items=[]){shape(label,[x,.6,z],[1.6,1.2,1.1],'wood');shape('Crate strap',[x,1.22,z],[.16,.08,1.15],'metal','cube',false);shape('Interaction marker',[x,2,z],[.22,.22,.22],'gold','sphere',false);return point(key,label,kind,[x,0,z],items);}
function cover(key,x,z,s){let o=shape(key,[x,s[1]/2,z],s,'stone');o.layer=8;point(key+'_cover','Vật chắn',6,[x,0,z]);}
function hide(x,z){point('hide_'+points.length,'Bụi rậm • C đi khom',5,[x,0,z],[],3.8);for(let i=0;i<7;i++){let a=i*6.28/7;shape('Tall fern',[x+Math.cos(a)*1.8,.45,z+Math.sin(a)*1.8],[2,.9,1.4],'grass','sphere',false);}}
shape('Forest floor • 90 × 148 m',[0,-.6,14],[90,1.2,148],'earth').layer=0;
shape('West boundary',[-45,2,14],[2,6,148],'stone');shape('East boundary',[45,2,14],[2,6,148],'stone');shape('South boundary',[0,2,-60],[90,6,2],'stone');shape('North bank',[0,2,88],[90,6,2],'stone');
const routes=[[[0,-52],[-3,-39],[0,-25],[1,-13],[0,2],[3,17],[0,31],[-3,40],[3,49],[4,62],[17,72],[27,79]],[[0,-25],[-13,-19],[-23,-7],[-24,8],[-18,21],[0,31]],[[0,-25],[16,-20],[24,-8],[23,9],[17,23],[0,31]]];
for(let r=0;r<routes.length;r++){let route=routes[r];for(let i=1;i<route.length;i++){let a=route[i-1],b=route[i],steps=Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1]));for(let j=0;j<=steps;j++){let t=j/steps;shape('Worn trail',[a[0]+(b[0]-a[0])*t,.012,a[1]+(b[1]-a[1])*t],[r===0?6:4,.012,5],'path','cylinder',false);}}}
function routeDistance(x,z){let min=1e5;for(let route of routes)for(let i=1;i<route.length;i++){let a=route[i-1],b=route[i],dx=b[0]-a[0],dz=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz)));min=Math.min(min,Math.hypot(x-a[0]-t*dx,z-a[1]-t*dz));}return min;}
let seed=1707;function rand(){seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;}
function clearing(x,z){return Math.hypot(x,z+49)<11||Math.hypot(x+3,z-36)<11||(Math.abs(x)<19&&z>47&&z<70)||Math.hypot(x-26,z-78)<11;}
for(let i=0;i<570;i++){let x=-42+rand()*84,z=-57+rand()*142;if(routeDistance(x,z)<5||clearing(x,z))continue;let h=4.3+rand()*3.7;shape('Forest trunk',[x,h/2,z],[.65,h,.65],'bark','cube');shape('Canopy',[x,h,z],[3.8,2.4,3.8],'leaf','sphere',false);if(i%3===0)shape('Moss rock',[x+1,.45,z+1],[2.4,1.2,1.6],'stone','sphere');}
for(let i=0;i<180;i++){let x=-40+rand()*80,z=-55+rand()*138;if(routeDistance(x,z)<3||clearing(x,z))continue;shape('Ground fern',[x,.25,z],[1.5,.5,1.2],'grass','sphere',false);}
for(let i=0;i<9;i++)hide(-19-Math.sin(i)*4,-15+i*5);for(let i=0;i<5;i++)hide(23,-14+i*7);
crate('supplies','Nhận hàng tiếp tế',0,-2,-49);crate('tutorial_loot','Túi vật tư bên đường',1,3,-37,[['cloth',4],['herb',2],['ammo_rifle',18]]);
shape('Supply shelter',[-7,2.5,-51],[5,.2,5],'canvas','cube',false);for(let x of[-9,-5])for(let z of[-53,-49])shape('Shelter pole',[x,1.25,z],[.15,2.5,.15],'wood');cover('Tutorial fallen log',-5,-31,[5,1.4,1.3]);
cover('Crossing west rock',-5,-8,[4,1.6,2.1]);cover('Crossing east rock',6,3,[4,1.7,2]);cover('Northern sandbags',-4,17,[5,1.3,1.4]);cover('Eastern fallen tree',17,5,[1.6,1.4,6]);shape('Abandoned supply cart',[9,.7,-5],[2.5,1.4,3.5],'wood');for(let i=0;i<3;i++)shape('Hollow metal cans',[15+i,.5,-11],[.6,.5,.6],'metal','cylinder',false);crate('east_cache','Vật tư lối vòng',1,28,13,[['cloth',2],['herb',1],['ammo_rifle',12]]);
shape('Field workbench',[-6,.6,36],[3,1.2,1.4],'wood');point('workbench','Bàn chế tạo • B làm băng cứu thương',2,[-6,0,36]);for(let i=0;i<9;i++){let a=i*Math.PI*2/9;shape('Cold fire ring',[2+Math.cos(a),.2,35+Math.sin(a)],[.6,.4,.6],'stone','sphere',false);}shape('Bedroll',[-1,.15,39],[1.2,.3,2.5],'canvas','cube',false);crate('rest_cache','Hộp y tế bỏ lại',1,-8,40,[['herb',2],['cloth',2]]);
shape('Base courtyard',[0,.03,58],[29,.06,22],'path','cube',false);shape('West ruined wall',[-14,1.2,58],[1,2.4,21],'stone');shape('East ruined wall',[14,1.2,55],[1,2.4,15],'stone');shape('South wall left',[-9,1,47],[10,2,1],'stone');shape('South wall right',[10,1,47],[8,2,1],'stone');shape('North broken wall',[-4,1.2,69],[21,2.4,1],'stone');shape('Command room north',[-5,1.5,65],[12,3,.5],'wood');shape('Command room west',[-11,1.5,61],[.5,3,8],'wood');shape('Command room floor',[-5,.04,61],[12,.08,8],'wood','cube',false);shape('Map table',[-5,.75,61],[3,1.5,1.8],'wood');shape('River topographic chart',[-5,1.51,61],[2.6,.02,1.45],'paper','cube',false);for(let i=0;i<5;i++){let o=shape('Secret river route',[-5.8+i*.4,1.53,61],[.04,.02,1.1],'metal','cube',false);o.rot=[0,i*13,0];}point('documents','Thu thập bản đồ và ghi chép bến sông',3,[-5,0,61]);shape('Evidence marker',[-5,2.7,61],[.28,.28,.28],'gold','sphere',false);shape('Empty weapon rack',[-10,1,63],[.4,2,3],'metal');for(let i=0;i<5;i++)shape('Empty ammunition crate',[6+i%2*2,.35,57+i*1.3],[1.4,.7,1],'wood');cover('Collapsed masonry',8,65,[3,1.1,2]);shape('Watch platform',[-17,3,65],[4,.3,4],'wood','cube',false);for(let i=0;i<4;i++)shape('Watchtower support',[-18+i%2*2,1.5,64+Math.floor(i/2)*2],[.25,3,.25],'wood');
shape('River',[0,-.1,98],[140,.1,25],'water','cube',false);for(let i=0;i<10;i++)shape('River glint',[-45+rand()*90,0,92+i*1.6],[5+rand()*15,.02,.08],'paper','cube',false);for(let i=0;i<12;i++)shape('Landing jetty plank',[27,.15,74+i*.7],[4,.3,.6],'wood','cube',false);shape('Moored boat',[32,.3,84],[2.5,.7,6],'wood','cube',false);point('river_exit','Giao hàng và rời rừng cùng Hùng',4,[27,0,80]);shape('Exit marker',[27,.08,80],[3,.035,3],'gold','cylinder',false);
function actor(name,p,mat,layer){let o=obj(name,p,[1,1,1],null,layer),visual=obj('VisualRoot',[0,0,0],[1,1,1],o);shape('Body placeholder',[0,.95,0],[.65,.8,.65],mat,'capsule',false,visual);shape('Helmet placeholder',[0,1.65,0],[.62,.4,.62],mat,'sphere',false,visual);shape('Backpack placeholder',[0,1,-.34],[.5,.65,.24],'canvas','cube',false,visual);shape('Rifle placeholder',[.3,1,.45],[.12,.15,.9],'metal','cube',false,visual);return o;}
function agent(o){comp(o,195,'NavMeshAgent','  m_Enabled: 0\n  m_AgentTypeID: 0\n  m_Radius: 0.4\n  m_Speed: 3.2\n  m_Acceleration: 14\n  avoidancePriority: 50\n  m_AngularSpeed: 240\n  m_StoppingDistance: 0.4\n  m_AutoTraverseOffMeshLink: 1\n  m_AutoBraking: 1\n  m_AutoRepath: 1\n  m_Height: 1.8\n  m_BaseOffset: 0\n  m_WalkableMask: 4294967295\n  m_ObstacleAvoidanceType: 4\n');}
const nam=actor('Nam • replace VisualRoot',[0,.05,-52],'nam',6);comp(nam,143,'CharacterController','  m_Material: {fileID: 0}\n  m_IncludeLayers:\n    serializedVersion: 2\n    m_Bits: 0\n  m_ExcludeLayers:\n    serializedVersion: 2\n    m_Bits: 0\n  m_LayerOverridePriority: 0\n  m_ProvidesContacts: 0\n  m_Enabled: 1\n  serializedVersion: 3\n  m_Height: 1.8\n  m_Radius: 0.35\n  m_SlopeLimit: 45\n  m_StepOffset: 0.3\n  m_SkinWidth: 0.08\n  m_MinMoveDistance: 0\n  m_Center: {x: 0, y: 0.9, z: 0}\n');const hung=actor('Hùng • narrative companion',[2,0,-51],'hung',0);agent(hung);
const patrols=[[[-2,-8],[4,-2],[1,7],[-6,0]],[[6,11],[-1,16],[-8,10],[0,5]],[[13,-9],[20,-2],[14,6],[9,-1]]];for(let i=0;i<patrols.length;i++){let pts=patrols[i],o=actor('Patrol '+(i+1),[pts[0][0],0,pts[0][1]],'enemy',7);agent(o);comp(o,136,'CapsuleCollider','  m_Material: {fileID: 0}\n  m_IsTrigger: 0\n  m_Enabled: 1\n  serializedVersion: 2\n  m_Radius: 0.4\n  m_Height: 1.8\n  m_Direction: 1\n  m_Center: {x: 0, y: 0.9, z: 0}\n');script(o,'ForestGuard','  id: patrol_'+i+'\n  patrol:\n'+pts.map(p=>'  - '+v([p[0],0,p[1]])+'\n').join('')+'  state: 0\n  hp: 0\n  suspicion: 0\n');guards.push(o);}
let original=fs.readFileSync(path.join(root,'Assets/_Project/Scenes/Maps/Map 1.unity'),'utf8');original=original.slice(0,original.indexOf('--- !u!1660057539'));
// Preserve Unity-authored scene settings and camera/light serialization, update only their values.
original=original.replace('  orthographic: 0','  orthographic: 1').replace('  orthographic size: 5','  orthographic size: 12').replace('  m_LocalPosition: {x: 0, y: 1, z: -10}','  m_LocalPosition: '+v([-18.371,15,-70.371])).replace('  m_LocalRotation: {x: 0, y: 0, z: 0, w: 1}','  m_LocalRotation: '+q([30,45,0])).replace('  m_AmbientMode: 0','  m_AmbientMode: 3').replace(/  m_AmbientSkyColor: .*/, '  m_AmbientSkyColor: {r: 0.51, g: 0.6, b: 0.54, a: 1}');
const mission=obj('00 • Map 1 mission');script(mission,'ForestMission','  player: {fileID: '+nam.tr+'}\n  hung: {fileID: '+hung.tr+'}\n  gameCamera: {fileID: 1109116645}\n  balanceJson: {fileID: 4900000, guid: '+meta(base+'/Map01Balance.json')+', type: 3}\n  contentBundle: {fileID: 4900000, guid: '+contentGuid+', type: 3}\n  trailMaterial: {fileID: 2100000, guid: '+matGuids.gold+', type: 2}\n');
let output=original;for(let o of objects){output+='--- !u!1 &'+o.go+'\nGameObject:\n  m_ObjectHideFlags: 0\n  m_CorrespondingSourceObject: {fileID: 0}\n  m_PrefabInstance: {fileID: 0}\n  m_PrefabAsset: {fileID: 0}\n  serializedVersion: 6\n  m_Component:\n'+o.components.map(c=>'  - component: {fileID: '+c+'}\n').join('')+'  m_Layer: '+o.layer+'\n  m_Name: '+JSON.stringify(o.name)+'\n  m_TagString: Untagged\n  m_Icon: {fileID: 0}\n  m_NavMeshLayer: 0\n  m_StaticEditorFlags: 0\n  m_IsActive: 1\n--- !u!4 &'+o.tr+'\nTransform:\n  m_ObjectHideFlags: 0\n  m_CorrespondingSourceObject: {fileID: 0}\n  m_PrefabInstance: {fileID: 0}\n  m_PrefabAsset: {fileID: 0}\n  m_GameObject: {fileID: '+o.go+'}\n  serializedVersion: 2\n  m_LocalRotation: '+q(o.rot)+'\n  m_LocalPosition: '+v(o.p)+'\n  m_LocalScale: '+v(o.scale)+'\n  m_ConstrainProportionsScale: 0\n  m_Children:'+(o.children.length?'\n'+o.children.map(c=>'  - {fileID: '+c+'}\n').join(''):' []\n')+'  m_Father: {fileID: '+(o.parent?o.parent.tr:0)+'}\n  m_LocalEulerAnglesHint: '+v(o.rot)+'\n';}output+=parts.join('');output+='--- !u!1660057539 &9223372036854775807\nSceneRoots:\n  m_ObjectHideFlags: 0\n  m_Roots:\n'+[1109116646,475667026,...roots].map(c=>'  - {fileID: '+c+'}\n').join('');
if(fs.existsSync(path.join(root,scene)))throw Error('Refusing to overwrite existing scene; use Unity builder to rebuild');write(scene,output);sweep(base);
const settings=path.join(root,'ProjectSettings/EditorBuildSettings.asset');let build=fs.readFileSync(settings,'utf8');if(!build.includes(scene)){build=build.replace('  m_configObjects:','  - enabled: 1\n    path: '+scene+'\n    guid: '+meta(scene)+'\n  m_configObjects:');fs.writeFileSync(settings,build);}
fs.mkdirSync(path.join(root,'Tools/Map01Reports'),{recursive:true});fs.writeFileSync(path.join(root,'Tools/Map01Reports/source-layout.json'),JSON.stringify({routes,shapes,points,objects:objects.length},null,2));
console.log(JSON.stringify({scene,objects:objects.length,components:parts.length,shapes:shapes.length,bytes:output.length}));
